# Generated by Django 5.1.3 on 2024-12-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
